### Client API Routes

### Create client(d)
POST http://localhost:8080/client-api/signin
Content-Type: application/json

{
  "name": "Devendra-Client",
  "email": "dev@client.com",
  "password": "dev-client",
  "companyName": "company-dev",
  "industry": "industry-dev",
  "contactInfo": "contact@company.dev.in"
}
### 67b75904b5da604dfe41b060

### Client login(d)
POST http://localhost:8080/client-api/login
Content-Type: application/json

{
  "email": "test22@gmail.com",
  "password": "qwerty123"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsInJvbGUiOiJjbGllbnQiLCJkYXRhIjp7Il9pZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsIm5hbWUiOiJEZXYiLCJjb21wYW55TmFtZSI6IkRldiBTb2x1dGlvbnMgLkx0ZCIsImluZHVzdHJ5IjoiVGVjaCIsImNvbnRhY3RJbmZvIjoiY29udGFjdEBkZXZzb2xzLmNvbSIsImVtYWlsIjoidGVzdDIyQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJjZXJ0aWZpY2F0aW9ucyI6W10sInN1YnNjcmlwdGlvblN0YXR1cyI6ZmFsc2UsImJhbGFuY2UiOjAsInN1YnNjcmlwdGlvbklkIjpudWxsLCJzdWJzY3JpcHRpb25EdXJhdGlvbkluRGF5cyI6MCwicmVwb3J0ZWRDb3VudCI6MCwiY3JlYXRlZEF0IjoiMjAyNS0wNC0xOFQxMzo0MDowNS44NThaIiwidXBkYXRlZEF0IjoiMjAyNS0wNC0xOFQxMzo0MDowNS44NThaIiwiX192IjowfSwiaWF0IjoxNzQ0OTgzNzExLCJleHAiOjE3NDUwNzAxMTF9.oOpvS5zeeyeec3WkiHaRIwGkCSGJVgsil8qOC4jnDOc

### Get all clients
GET http://localhost:8080/client-api/clients

### Get client by ID
GET http://localhost:8080/client-api/clients/67b75852b5da604dfe41b056

### Update client profile
PUT http://localhost:8080/client-api/clients/67b75904b5da604dfe41b060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsInJvbGUiOiJjbGllbnQiLCJkYXRhIjp7Il9pZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsIm5hbWUiOiJEZXYiLCJjb21wYW55TmFtZSI6IkRldiBTb2x1dGlvbnMgLkx0ZCIsImluZHVzdHJ5IjoiVGVjaCIsImNvbnRhY3RJbmZvIjoiY29udGFjdEBkZXZzb2xzLmNvbSIsImVtYWlsIjoidGVzdDIyQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJjZXJ0aWZpY2F0aW9ucyI6W10sInN1YnNjcmlwdGlvblN0YXR1cyI6ZmFsc2UsImJhbGFuY2UiOjAsInN1YnNjcmlwdGlvbklkIjpudWxsLCJzdWJzY3JpcHRpb25EdXJhdGlvbkluRGF5cyI6MCwicmVwb3J0ZWRDb3VudCI6MCwiY3JlYXRlZEF0IjoiMjAyNS0wNC0xOFQxMzo0MDowNS44NThaIiwidXBkYXRlZEF0IjoiMjAyNS0wNC0xOFQxMzo0MDowNS44NThaIiwiX192IjowfSwiaWF0IjoxNzQ0OTgzNzExLCJleHAiOjE3NDUwNzAxMTF9.oOpvS5zeeyeec3WkiHaRIwGkCSGJVgsil8qOC4jnDOc
Content-Type: application/json

{
  "name": "Dev-Client",
  "certifications":["certificate-1","certificate-2"]
}

### Delete client profile
DELETE http://localhost:8080/client-api/clients/67b75852b5da604dfe41b056
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1ODUyYjVkYTYwNGRmZTQxYjA1NiIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkwMDQsImV4cCI6MTc0MDE1NTQwNH0.GawlyxS4ty94nHPwZnhyo4tnhod0tZb2kqY2Q75kq0k


### Create job(d)
POST http://localhost:8080/client-api/post-job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
Content-Type: application/json

{
  "title": "Website Development",
  "description": "Develop a responsive e-commerce website.",
  "clientId": "67b75852b5da604dfe41b056",
  "budget": 5000,
  "type": "online",
  "status": "in-progress",
  "teamRequired": true,
  "milestones": [
    {
      "title": "Design Phase",
      "description": "Create UI/UX design",
      "amount": 1500,
      "dueDate": "2024-03-01"
    },
    {
      "title": "Development Phase",
      "description": "Code the website",
      "amount": 2500,
      "dueDate": "2024-04-01"
    },
    {
      "title": "Deployment",
      "description": "Launch the website",
      "amount": 1000,
      "dueDate": "2024-05-01"
    }
  ]
}




### Get all jobs(d)
GET http://localhost:8080/client-api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDA0ODA2MjksImV4cCI6MTc0MDU2NzAyOX0.XEPUimSgUXYPmRTfUYkI-dTn0jpO75GlqgnV1m0KcxU

### Get job by ID(d)
GET http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176

### Update job
PUT http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
Content-Type: application/json

{
  "title": "Web Development - Updated"
}

### Delete job
DELETE http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176

### Update MileStone Status
PUT http://localhost:8080/client-api/jobs/68025b669c2f71cdca8d6034/milestones/68025b669c2f71cdca8d6036
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsInJvbGUiOiJjbGllbnQiLCJkYXRhIjp7Il9pZCI6IjY4MDI1NjM1OWMyZjcxY2RjYThkNjAyMyIsIm5hbWUiOiJUZXN0LTIyIiwiY29tcGFueU5hbWUiOiJEZXYgU29sdXRpb25zIC5MdGQiLCJpbmR1c3RyeSI6IlRlY2giLCJjb250YWN0SW5mbyI6ImNvbnRhY3RAZGV2c29scy5pbiIsImVtYWlsIjoidGVzdDIyQGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnQiLCJjZXJ0aWZpY2F0aW9ucyI6WyJDZXJ0LTEiXSwic3Vic2NyaXB0aW9uU3RhdHVzIjpmYWxzZSwiYmFsYW5jZSI6MCwic3Vic2NyaXB0aW9uSWQiOm51bGwsInN1YnNjcmlwdGlvbkR1cmF0aW9uSW5EYXlzIjowLCJyZXBvcnRlZENvdW50IjowLCJjcmVhdGVkQXQiOiIyMDI1LTA0LTE4VDEzOjQwOjA1Ljg1OFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA0LTE4VDE3OjQ3OjA0Ljg2OVoiLCJfX3YiOjB9LCJpYXQiOjE3NDUwMDAxNjAsImV4cCI6MTc0NTA4NjU2MH0.JPMU7B3NkeSYOkK6t27Cah1HoWksyFwbjSQsjsOqevM
Content-Type: application/json

{
  "status": "completed"
}

### Get gigs for job and finalize freelancer(d)
GET http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176/gigs

### Post confirm freelancer
POST http://localhost:8080/client-api/jobs/68025b669c2f71cdca8d6034/confirm-gig/680255769c2f71cdca8d5fe1


### get all client subscriptions(d)
GET http://localhost:8080/client-api/subscriptions

### buying subscription
POST http://localhost:8080/client-api/buy-subscription/67b5d9196ea3454876456d43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k

###report a freelancer
POST http://localhost:8080/client-api/report-freelancer/67b4d207523a219b2e99ebdb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k

###
GET http://localhost:8080/freelancer-api/freelancers