### Client API Routes

### Create client(d)
POST http://localhost:8080/client-api/signin
Content-Type: application/json

{
  "name": "Devendra-Client",
  "email": "dev@client.com",
  "password": "dev-client",
  "companyName": "company-dev",
  "industry": "industry-dev",
  "contactInfo": "contact@company.dev.in"
}
### 67b75904b5da604dfe41b060

### Client login(d)
POST http://localhost:8080/client-api/login
Content-Type: application/json

{
  "email": "dev@client.com",
  "password": "dev-client"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k

### Get all clients
GET http://localhost:8080/client-api/clients

### Get client by ID
GET http://localhost:8080/client-api/clients/67b75852b5da604dfe41b056

### Update client profile
PUT http://localhost:8080/client-api/clients/67b75904b5da604dfe41b060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
Content-Type: application/json

{
  "name": "Dev-Client",
  "certifications":["certificate-1","certificate-2"]
}

### Delete client profile
DELETE http://localhost:8080/client-api/clients/67b75852b5da604dfe41b056
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1ODUyYjVkYTYwNGRmZTQxYjA1NiIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkwMDQsImV4cCI6MTc0MDE1NTQwNH0.GawlyxS4ty94nHPwZnhyo4tnhod0tZb2kqY2Q75kq0k


### Create job(d)
POST http://localhost:8080/client-api/post-job
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
Content-Type: application/json

{
  "title": "Website Development",
  "description": "Develop a responsive e-commerce website.",
  "clientId": "67b75852b5da604dfe41b056",
  "budget": 5000,
  "type": "online",
  "status": "in-progress",
  "teamRequired": true,
  "milestones": [
    {
      "title": "Design Phase",
      "description": "Create UI/UX design",
      "amount": 1500,
      "dueDate": "2024-03-01"
    },
    {
      "title": "Development Phase",
      "description": "Code the website",
      "amount": 2500,
      "dueDate": "2024-04-01"
    },
    {
      "title": "Deployment",
      "description": "Launch the website",
      "amount": 1000,
      "dueDate": "2024-05-01"
    }
  ]
}




### Get all jobs(d)
GET http://localhost:8080/client-api/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDA0ODA2MjksImV4cCI6MTc0MDU2NzAyOX0.XEPUimSgUXYPmRTfUYkI-dTn0jpO75GlqgnV1m0KcxU

### Get job by ID(d)
GET http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176

### Update job
PUT http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
Content-Type: application/json

{
  "title": "Web Development - Updated"
}

### Delete job
DELETE http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176

### Get gigs for job and finalize freelancer(d)
GET http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176/gigs

### Post confirm freelancer
POST http://localhost:8080/client-api/jobs/67b75ea7ce2c05b5a4094176/confirm-gig/67b76222261b0e2d253fa130


### get all client subscriptions(d)
GET http://localhost:8080/client-api/subscriptions

### buying subscription
POST http://localhost:8080/client-api/buy-subscription/67b5d9196ea3454876456d43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k

###report a freelancer
POST http://localhost:8080/client-api/report-freelancer/67b4d207523a219b2e99ebdb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc1OTA0YjVkYTYwNGRmZTQxYjA2MCIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDAwNjkxNzgsImV4cCI6MTc0MDE1NTU3OH0.yZZej-xF30Waag-RtOqDVtU8C1npeHaSBK5yVYFTC0k
