### Freelancer API Routes

### Create freelancer
POST http://localhost:8080/freelancer-api/signup
Content-Type: application/json

{
  "name": "Devendra",
  "email": "dev@gmail.com",
  "password": "devendra",
  "skills": ["ReactJS","Javascript","TailwindCSS"],
  "experience": "4 years"

}
### 67b76222261b0e2d253fa130

### Freelancer login
POST http://localhost:8080/freelancer-api/login
Content-Type: application/json

{
  "email": "dev@gmail.com",
  "password": "devendra"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA


### Get all freelancers
GET http://localhost:8080/freelancer-api/freelancers

### Get freelancer by ID
GET http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130

### Update freelancer profile
PUT http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA
Content-Type: application/json

{
  "name": "Devendra Yalamaddi",
  "skills":[
    "MERN",
    "NextJS",
    "C++"
  ],
  "certifications":["certificate-1","certificate-2"]
}

### Delete freelancer profile
DELETE http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA

### Create gig
POST http://localhost:8080/freelancer-api/gigs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA
Content-Type: application/json

{
  "title": "Website optimization",
  "jobID":"67b75ea7ce2c05b5a4094176",
  "description": "I can optimise the website",
  "price": 700
}

### get gigs
GET http://localhost:8080/freelancer-api/gigs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA


### Team creation
POST http://localhost:8080/freelancer-api/teams/new-team
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI
Content-Type: application/json

{
  "teamName":"Dream-Developers",
  "teamMembers":["67b7f96e57eca2278f4bc03f"]
}

### get teams
GET http://localhost:8080/freelancer-api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI


### get team by ID
GET http://localhost:8080/freelancer-api/teams/67b8085579591b4efc280973
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI

### update the team
PUT http://localhost:8080/freelancer-api/teams/update-team/67b8085579591b4efc280973
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI
Content-Type: application/json

{
  "updatedDetails":{
    "teamName":"Dream-Developers- updated",
    "teamMembers":["67b7f96e57eca2278f4bc03f"]
  }
}

### delete a team
DELETE http://localhost:8080/freelancer-api/teams/delete-team/67b8085579591b4efc280973
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI

### get all freelancer subscriptions
GET http://localhost:8080/freelancer-api/subscriptions
### buying subscription
POST http://localhost:8080/freelancer-api/buy-subscription/67b5d63d6ea3454876456d3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA
###report a client
POST http://localhost:8080/freelancer-api/report-client/67b75904b5da604dfe41b060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA