### Freelancer API Routes

### Create freelancer(d)
POST http://localhost:8080/freelancer-api/signup
Content-Type: application/json

{
  "name": "Devendra",
  "email": "dev@gmail.com",
  "password": "devendra",
  "skills": ["ReactJS","Javascript","TailwindCSS"],
  "experience": "4 years"
}
### 67b76222261b0e2d253fa130

### Freelancer login(d)
POST http://localhost:8080/freelancer-api/login
Content-Type: application/json

{
  "email": "test23@gmail.com",
  "password": "qwerty123"
}
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA


### Get all freelancers
GET http://localhost:8080/freelancer-api/freelancers

### Get freelancer by ID
GET http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130

### Update freelancer profile
PUT http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQyODM0MTM2LCJleHAiOjE3NDI5MjA1MzZ9.LIPkjYpsnWy_7PiA0bfJO2F_FFfxRdDp92tXz-ccA2g
Content-Type: application/json

{
  "name": "Devendra-updated",
  "skills":[
    "MERN",
    "NextJS",
    "C++"
  ],
  "certifications":["certificate-1","certificate-2"]
}

### Delete freelancer profile
DELETE http://localhost:8080/freelancer-api/freelancers/67b76222261b0e2d253fa130
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA

### get jobs
GET http://localhost:8080/freelancer-api/job-posts


### Create gig
POST http://localhost:8080/freelancer-api/gigs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA
Content-Type: application/json

{
  "title": "Website optimization",
  "jobID":"67b75ea7ce2c05b5a4094176",
  "description": "I can optimise the website",
  "price": 700
}

### get gigs
GET http://localhost:8080/freelancer-api/gigs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwNzE0NzQxLCJleHAiOjE3NDA4MDExNDF9.-RnoIwG1BTmm1hv_UVsoTIvjCSP0fkdOyaGA97Ds9fA

### withdraw gig
DELETE http://localhost:8080/freelancer-api/gigs/6802560a9c2f71cdca8d6014
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDI1NTc2OWMyZjcxY2RjYThkNWZlMSIsInJvbGUiOiJmcmVlbGFuY2VyIiwiZGF0YSI6eyJfaWQiOiI2ODAyNTU3NjljMmY3MWNkY2E4ZDVmZTEiLCJuYW1lIjoiRGV2ZW5kcmEiLCJlbWFpbCI6InRlc3QyMkBnbWFpbC5jb20iLCJjZXJ0aWZpY2F0aW9ucyI6W10sInN1YnNjcmlwdGlvblN0YXR1cyI6ZmFsc2UsInN1YnNjcmlwdGlvbklkIjpudWxsLCJzdWJzY3JpcHRpb25EdXJhdGlvbkluRGF5cyI6MCwiYmFsYW5jZSI6MCwic2tpbGxzIjpbIlJlYWN0SnMiLCJOZXh0SlMiXSwiZXhwZXJpZW5jZSI6InF3ZXJ0eXVpb3AiLCJyZXBvcnRlZENvdW50IjowLCJyb2xlIjoiZnJlZWxhbmNlciIsInBvcnRmb2xpbyI6IiIsImNyZWF0ZWRBdCI6IjIwMjUtMDQtMThUMTM6MzY6NTQuMzU4WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDQtMThUMTM6MzY6NTQuMzU4WiIsIl9fdiI6MH0sImlhdCI6MTc0NTA3NTQxNywiZXhwIjoxNzQ1MTYxODE3fQ.Qn5mHRpvN6GQBEk-d9MsNxBtZ30VQq8ZD3BQr90Qujg

### Team creation
POST http://localhost:8080/freelancer-api/teams/new-team
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI
Content-Type: application/json

{
  "teamName":"Dream-Developers",
  "teamMembers":["67b7f96e57eca2278f4bc03f"]
}

### get teams
GET http://localhost:8080/freelancer-api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI


### get team by ID
GET http://localhost:8080/freelancer-api/teams/6804deec1aaca235a4afd26f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDRkZWJjMWFhY2EyMzVhNGFmZDI1ZSIsInJvbGUiOiJmcmVlbGFuY2VyIiwiZGF0YSI6eyJfaWQiOiI2ODA0ZGViYzFhYWNhMjM1YTRhZmQyNWUiLCJuYW1lIjoiVGVzdGVyIiwiZW1haWwiOiJ0ZXN0MjNAZ21haWwuY29tIiwiY2VydGlmaWNhdGlvbnMiOltdLCJzdWJzY3JpcHRpb25TdGF0dXMiOmZhbHNlLCJzdWJzY3JpcHRpb25JZCI6bnVsbCwic3Vic2NyaXB0aW9uRHVyYXRpb25JbkRheXMiOjAsImJhbGFuY2UiOjAsInNraWxscyI6WyJTMSIsIlMyIl0sImV4cGVyaWVuY2UiOiJFLWluZiIsInJlcG9ydGVkQ291bnQiOjAsInJvbGUiOiJmcmVlbGFuY2VyIiwicG9ydGZvbGlvIjoiaHR0cHM6Ly9kZXZlbmRyYS15YWxhbWFkZGkudmVyY2VsLmFwcC8iLCJjcmVhdGVkQXQiOiIyMDI1LTA0LTIwVDExOjQ3OjA4LjgxOFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA0LTIwVDExOjQ3OjA4LjgxOFoiLCJfX3YiOjB9LCJpYXQiOjE3NDUxNTA1NDMsImV4cCI6MTc0NTIzNjk0M30.fDSeU-6CnnwmcpStPEiNweKJOeuwtL-FEGGbkbnsjSU

### update the team
PUT http://localhost:8080/freelancer-api/teams/update-team/67b8085579591b4efc280973
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI
Content-Type: application/json

{
  "updatedDetails":{
    "teamName":"Dream-Developers- updated",
    "teamMembers":["67b7f96e57eca2278f4bc03f"]
  }
}

### delete a team
DELETE http://localhost:8080/freelancer-api/teams/delete-team/67b8085579591b4efc280973
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMTEwMjE4LCJleHAiOjE3NDAxOTY2MTh9.wFS2PrIV5JEJ-AjEyGMByX6V63NneDHJ2wOa_ZlrsLI

### get all freelancer subscriptions
GET http://localhost:8080/freelancer-api/subscriptions
### buying subscription
POST http://localhost:8080/freelancer-api/buy-subscription/67b5d63d6ea3454876456d3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA
###report a client
POST http://localhost:8080/freelancer-api/report-client/67b75904b5da604dfe41b060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yjc2MjIyMjYxYjBlMmQyNTNmYTEzMCIsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQwMDcxNDcyLCJleHAiOjE3NDAxNTc4NzJ9.Cjd_hbia7MtoARepCaZcBXO0MhjBLmv4Q5gOHapvxHA